### ISSUE TITLE
Mercury+ ST1

### ISSUE THREAD

**Issue by proconsule** [enclustra-bsp/bsp-altera#2]
Please can you add support for Mercury+ ST1. Thanks

**Comment by tholzsche** [comment]
Hi, we are on a major update (including U-Boot, Linux, ST1, ...). Hopefully it will be released soon, until then please use the PE1 target for your ST1. Greets Till

**Comment by proconsule** [comment]
i tried but with no luck.

U-Boot 2014.10 (Jan 26 2018 - 00:24:27)

CPU   : Altera SOCFPGA Arria 10 Platform
BOOT  : SD/MMC External Transceiver (1.8V)
BOARD : Enclustra Mercury+ AA1
I2C:   ready
DRAM:  WARNING: Caches not enabled
SOCFPGA DWMMC: 0
Error - fpga.rbf not found within SDMMC.
INFO  : Skip relocation as SDRAM is non secure memory
Reserving 2048 Bytes for IRQ stack at: ffe386e8
data abort
pc : [<ffe00cc2>]          lr : [<ffe02331>]
sp : ffe3def8  ip : 0000001c     fp : 00000001
r10: ffd02078  r9 : ffe3ff38     r8 : ffe00054
r7 : ffe258fc  r6 : ffe258a8     r5 : 00000000  r4 : ffffd000
r3 : ffcfb000  r2 : 00000002     r1 : 00000001  r0 : 00000001
Flags: nzcv  IRQs off  FIQs off  Mode SVC_32
Resetting CPU ...


the fpga.rbf is on the fat32 boot partition with all other needed files (uboot.scr uImage and so on).

any advice?

**Comment by proconsule** [comment]
also the buildroot fail

make enclustra_altera_uart1_defconfig completed successfully
+make EBE_OVERLAYS=/home/ceco/enclustra/bsp-altera/out_20220704105125_Mercury_AA1_Mercury_PE1_Rev2_MMC/overlays -j25
ERROR: Error running make EBE_OVERLAYS={ebe_overlays} -j25 for Buildroot
INFO: Getting binary boot_files_sx270_e3

the internal error is

 GEN      charset.alias
          GEN      ref-add.sed
          GEN      ref-del.sed
          CC       glthread/lock.o
        freadahead.c: In function 'freadahead':
        freadahead.c:92:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
          #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
           ^~~~~
        fseeko.c: In function 'rpl_fseeko':
        fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
           #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."

here.


also inside the build.log there are many many errors (probably to outdated code used)

This build system NEED an update because is usesless right now for altera deivces. (noted that the xylinx one is much updated compared to this one)

**Comment by proconsule** [comment]
found out that my 32gb sdcard is not working (probably due to the old uboot) using an old 8gb it program the fpga.rbf but

- no mac address will be set on linux side (it uses 00:00:00:00:00:00 so no dhcp)
- i have to manualy disable usb from dtb because goes on an endless loop with overcurrent error on dwc2
- the kernel image built by the build system is very restricted (no ext4 support in 2022 is absurd)
- uboot on arria10 module is shipped as binary (it will be useful to have the source)

so far too many issue for a production board.

**Comment by andreas-buerkler-enclustra** [comment]
Hello

Unfortunately the Linux BSP was not undated for several years. We are currently working on a update which will be released in the near future.

- To build Buildroot, Ubuntu 18 or older is required. Never versions provide a glibc version that is not compatible.
- The overcurrent messages are because USB VBUS is missing on the USB PHY input. Unfortunately this signal is connected to the USB B connector for device operation. As workaround you can provide VBUS by connecting USB B connector to your PC. Make sure the DIP switches for USB MODE are set correctly on the ST1 base board.
- The U-Boot sources can be found in following repository: https://github.com/enclustra/altera-arria10-uboot

Best regards,
Andreas

**Comment by proconsule** [comment]
Thanks for the info, the usb is a big issue (an HW issue). i resolved the mac address issue compiling myself a kernel 5.7 from altera-linux kernel source.
i compiled all the devices support not as modules but compiled on kernel itself (this make very easy to test andh check kernel revision since no need to update the lib/modules directory.
also the ext4 is supported right now.

i attach the kernel config i am using right now. (if someone want to compile it)

[config-kernel-5.7.txt](https://github.com/enclustra-bsp/bsp-altera/files/9062036/config-kernel-5.7.txt)

**Comment by proconsule** [comment]
I noted also that SFP+ cage is left unsolderd. I look at the schematics of ST1 and AA1 module and seems like the USB3 FX controller is using the pin on connector C that is used for SFP operation.
Is not possible to use SFP+ with AA1 module right?

**Comment by tholzsche** [comment]
Yes, the SFP cage is press-fit, and the FX3 unfortunately occupies the SFP pins. Please contact our [support service](https://www.enclustra.com/en/support/) for general questions about our products and their capabilities. Greets Till
