### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by vector91** [enclustra-bsp/bsp-altera#4]
The link to the documentation (http://enclustra.github.io/ebe-docs/user-doc-altera/index_altera.html) seems to be broken. Has it been moved to somwhere else?

**Comment by EnclustraRaivis** [comment]
Hi,
Thank you for reporting this issue. Now link is restored. Let us know if there is some with it.

**Comment by vector91** [comment]
It now works, thanks!
